<form id="connect_user" class="form-vertical" enctype="application/x-www-form-urlencoded"
      action="<?php echo $this->escape($this->element->getAction()); ?>" 
      method="<?php echo $this->escape($this->element->getMethod()); ?>">
    <fieldset id="fieldset-connect_user">
        <div class="control-group">
            <div class="controls">
<!--                <input type="text" name="login" id="login" value="" placeholder="Identifiant">-->
                <?php echo $this->element->login->renderViewHelper(); ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
<!--                <input type="password" name="password" id="password" value="" placeholder="Mot de passe">-->
                <?php echo $this->element->password->renderViewHelper(); ?>
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" name="submit" id="submitbutton" value="Connexion" class="btn btn-primary">
        </div>
    </fieldset>
</form>