
<div>
   <?php echo $this->decorators; ?>
    <?php echo $this->element->IdMessageParent->renderViewHelper(); ?>
   <?php echo $this->element->message->renderViewHelper(); ?>
   <?php echo $this->element->envoyer->renderViewHelper(); ?>
</div>



    
<!--ANCIEN CODE
<?php echo $this->decorators; ?>
<?php echo $this->element->IdMessageParent->renderViewHelper(); ?>

<div class="control-group">
<div class="controls">
<?php echo $this->element->message->renderViewHelper(); ?>
</div>
</div>
<div class="control-group">
<div class="controls">
<?php echo $this->element->choixProfil->renderViewHelper(); ?>
</div>
</div>-->
        
            
      
