


<form class="form-vertical" enctype="application/x-www-form-urlencoded" 
      action="<?php echo $this->escape($this->element->getAction()); ?>" 
      method="<?php echo $this->escape($this->element->getMethod()); ?>">

        <?php echo $this->decorators; ?>
        <?php echo $this->element->IdMessageParent->renderViewHelper(); ?>
        
       <div><?php echo $this->element->message->renderViewHelper(); ?></div>



    
    <!--<fieldset>
        <?php echo $this->decorators; ?>
        <?php echo $this->element->IdMessageParent->renderViewHelper(); ?>
        
        <div class="control-group">
            <div class="controls">
                <?php echo $this->element->message->renderViewHelper(); ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <?php echo $this->element->choixProfil->renderViewHelper(); ?>
            </div>
        </div>
        <div class="form-actions">
            <?php echo $this->element->envoyer->renderViewHelper(); ?>
        </div>
    </fieldset>-->
</form>