<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<?php echo $this->form; ?>
<div class="vide"></div>
<div id="welcome">
    <h1>Bienvenue dans <span id="zf-name">COMULIEN !</span></h1>

    <h3>Page d'accueil</h3>

    <div id="more-information">
        
        <p>Application en cours de développement...</p><br/>
        <p>
            Docs Links: <br />
            <a href="https://docs.google.com/spreadsheet/ccc?key=0ArwLgJHmrEumdHNoN1ZMYTNPZEdyNDZmT3FMLTVMblE&pli=1#gid=0">Doc d'avancement</a> |
            <a href="https://docs.google.com/document/d/1kp0UgLQMYWwq5cKacDkxZ7DoIIjjT5Eoz69Xow8tTak/edit">Doc astuces/informations</a>
        </p>
        <p>
            Auteurs : <br />
        <p>Fred Horn - AlexSolex</p>
        </p>
    </div>
</div>