<div class="container">  
    <!-- Main hero unit for a primary marketing message or call to action --> 
    <!--div class="row">
        <div class="alert fade in">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>Travaux!</strong> RER E:Tx Hausmann/Tournan 28 au 31oct et 03 au 04nov.        </div>
    </div-->
    <div class="row">
        <div class="span6">
            <!--img src="img/logo_comulien_no_bg.png"-->
        </div>
        <div class="span6">
            <form class="form-search">
                <input id="gare" class="input-block-level" type="text" placeholder="Gare, nom de train..." data-provide="typeahead" data-items="4" data-source="["Gare du Nord","Gare de Lyon","gare de L'Est"]">
                       <button type="submit" class="btn input-block-level">Rechercher</button>
            </form>
        </div>
    </div>
    <div class="nomdegare">
        <h2><img class ="img-icon" src="img/SNC_Illu_Batiment_3-02.png"> Gare de Lyon</h2>
        <p>
        <table class="table table-striped table-hover">
            <tr>
                <th colspan="2" >
                    Prochains départs
                </th>
            </tr>
            <tr>
                <td><a href="#">GAME - Montargis</a></td>
                <td class="col-icon"><span class="badge badge-info">2</span></td>
            </tr>
            <tr>
                <td><a href="#">YAMO -  Moret</a></td>
                <td class="col-icon"><span class="badge badge-info">8</span></td>
            </tr>
            <tr>
                <td><a href="#">ZODO - Melun</a></td>
                <td class="col-icon"></td>
            </tr>
            <tr>
                <td><a href="#">KAMO - Montereau</a></td>
                <td class="col-icon"><span class="badge badge-info">5</span></td>
            </tr>

        </table>
        </p>
    </div>
    <div class="row">
        
    </div>
    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
    <script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-typeahead.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            var listeGares = ['Gare du Nord', 'Gare de Lyon', 'Gare de l\'Est'].sort();
            $('#gare').typeahead({source: listeGares, items:5});
        });
    </script>
</div>

