<?php
$evenement = $this->evenement;
$organisateur = $this->organisateur;
$helperUrl = new Zend_View_Helper_Url ( );
$lienListerTous = $helperUrl->url ( array ('action' => 'lister-tous', 'controller' => 'message' ) ); 
$lienListerOrganisateur = $helperUrl->url ( array ('action' => 'lister-organisateur', 'controller' => 'message' ) ); 
//var_dump($this->getEngine());
$comulienNamespace = new Zend_Session_Namespace('bulle');
$event = $comulienNamespace->checkedInEvent;
?>
<div id="view-content">
          <div id="nomOrga"><p><?php echo $this->escape($organisateur->nomOrga) ?></p></div>
          <div id="logoOrga"><img src="<?php echo $this->escape($organisateur->logoOrga) ?>" alt="logo" /></div>
          <div>Description : <?php echo $this->escape($organisateur->descOrga) ?>
          <p><a href="<?php echo $lienListerOrganisateur ?>" alt="">Voir les annonces organisateurs</a></p><div>

  <p>Vous présente</p>
          <div id="nomEvent"><?php echo $event->titreEvent ?> </div>
          <div id="logoOrga"><img src="<?php echo $this->escape($evenement->logoEvent) ?>" alt="logo Evènement" /></div>
          <div>Description : <?php echo $this->escape($evenement->descEvent) ?>
          <p><?php echo $this->datesEvenement($evenement->dateDebutEvent,$evenement->dateFinEvent,$evenement->delaiPersistence) ?></p>
      <p><a href="<?php echo $lienListerTous ?>" alt="">Voir les messages</a></p></div>

  
</div>
