<br /><br />
<div id="view-content">
	<p>View script for controller <b>Evenement</b> and script/action name <b>index</b></p>
</div>
Evenement Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <p>---------------------------------------------------------------------------------</p>
    <dt><?php echo $this->escape($entry->titreEvent) ?></dt>
    <dd><?php echo $this->escape($entry->numEvent) ?></dd>
    <dd><?php echo $this->escape($entry->descEvent) ?></dd>
    <dd><?php echo $this->escape($entry->logoEvent) ?></dd>
    <dd><?php echo $this->escape($entry->dateDebutEvent) ?></dd>
    <dd><?php echo $this->escape($entry->dateFinEvent) ?></dd>
    <dd><?php echo $this->escape($entry->delaiPersistence) ?></dd>
    <dd><?php if($entry->idOrga != null) echo 'Organisme : ' . $this->escape($entry->getOrga()->nomOrga)?></dd>
   
    <?php endforeach ?>
</dl>