<br /><br />
<div id="view-content">
	<p>Ceci est la page d'accueil <b>Evenement</b> accessible par une <b>URL</b></p>
</div>
Evenement Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <?php //var_dump($entry) ?>
    <p>---------------------------------------------------------------------------------</p>
    <dt><a href="<?php echo $this->url(array('controller' => 'evenement','action'=>'checkin','id'=>$entry->idEvent)); ?>" alt=""><?php echo $this->escape($entry->titreEvent) ?></a></dt>
    <dd><?php echo $this->escape($entry->numEvent) ?></dd>
    <dd><?php echo $this->escape($entry->descEvent) ?></dd>
    <dd><?php echo $this->escape($entry->logoEvent) ?></dd>
    <dd><?php echo $this->escape($entry->dateDebutEvent) ?></dd>
    <dd><?php echo $this->escape($entry->dateFinEvent) ?></dd>
    <dd><?php echo $this->escape($entry->delaiPersistence) ?></dd>
    <dd><?php if($entry->idOrga != null) echo 'Organisme : ' . $this->escape($entry->getOrga()->nomOrga)?></dd>
   
    <?php endforeach ?>
</dl>