<br /><br />
<div id="view-content">
	<p>View script for controller <b>Organisme</b> and script/action name <b>index</b></p>
</div>
Organisme Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><?php echo $this->escape($entry->nomOrga) ?></dt>
    <dd><?php echo $this->escape($entry->descOrga) ?></dd>
    <dd><?php echo $this->escape($entry->logoOrga) ?></dd>
    <?php endforeach ?>
</dl>