<a href="#myModal" role="button" class="btn" data-toggle="modal">Lancer une discussion</a>
 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Nouvelle discussion</h3>
  </div>
  <div class="modal-body">
    <p>Salut, on est trois en voiture de tête et on cherche un quatrième pour faire une belote...</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Fermer</button>
    <button class="btn btn-primary">Envoyer</button>
  </div>
</div>
<div id="container">
    <div class="nomdegare">
        <h2>POPI</h2>
        <img src="img/SNC_Illu_Transport_10-02.png">
    </div>
    <div class="row">
        <div class="span4">
            <div class="discussion">
                <div class="avatar">
                    <img src="img/fred.jpeg">
                </div>
                <div class="message">
                    <p><span class="pseudo">Fredo</span> <span class="heure">il y'a 22mn</span>
                        <br>Ca fait 10minutes qu'on est coincé! J'en ai marre que se passe-il?
                        <br> <span class="label label-info">8 réponses</span> <span class="label label-success">cool</span> <span class="label label-warning">booh</span>
                    </p>
                    <div class="row">
                        <div class="alert fade in">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>Reponse SNCF:</strong> Obstacle sur la voie à Chatelet, réprise de la circulation dans 15mn        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="span4">
            <div class="discussion">
                <div class="avatar">
                    <img src="img/laurent.jpeg">
                </div>
                <div class="message">
                    <p><span class="pseudo">Laurent Soyris</span> <span class="heure">il y'a 12mn</span>
                        <br>Je recherche quelqu'un pour faire du covoiturage... Répondez si vous avez un plan!
                        <br> <span class="label label-info">7 réponses</span> <span class="label label-success">cool</span> <span class="label label-warning">booh</span>
                    </p>
                </div>
            </div>
        </div>
        <div class="span4">
            <div class="discussion">
                <div class="avatar">
                    <img src="img/alex.jpeg">
                </div>
                <div class="message">
                    <p><span class="pseudo">Alexsolex</span> <span class="heure">il y'a 5mn</span>
                        <br>quelqu'un a de quoi charger un iPhone?
                        <br> <span class="label label-info">1 réponses</span> <span class="label label-success">cool</span> <span class="label label-warning">booh</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>