<div id="container">
    <div class="nomdegare">
        <h2>POPI</h2>
        <img src="img/SNC_Illu_Transport_10-02.png">
        <p>
        <table class="table table-striped table-hover">
            <tr>
                <th colspan="2" >
                    Discussions en cours
                </th>
            </tr>
            <tr>
                <td><a href="#">Recherce</a></td>
                <td class="col-icon"><span class="badge badge-info">2</span></td>
            </tr>
            <tr>
                <td><a href="#">YAMO -  Moret</a></td>
                <td class="col-icon"><span class="badge badge-info">8</span></td>
            </tr>
            <tr>
                <td><a href="#">ZODO - Melun</a></td>
                <td class="col-icon"></td>
            </tr>
            <tr>
                <td><a href="#">KAMO - Montereau</a></td>
                <td class="col-icon"><span class="badge badge-info">5</span></td>
            </tr>

        </table>
        </p>
    </div>
    <div class="hero-unit">
        <h2>Terminus Saint-Lazare</h2>
        <img src="img/SNC_Illu_Transport_10-02.png">
        <h2>Train: POPI</h2>
    </div>
    <div class="accordion" id="accordion2">
        <div class="accordion-group">
            <div class="accordion-heading accordion-toggle" data-parent="#accordion2" data-toggle="collapse"  href="#collapse<?php echo $parent["IDMESSAGE"] ?>">
                <table class="table table-bordered table-hover table-striped">
                    <tr>
                        <td><span class="badge badge-important">10</span> Titre de la dsicussion</td>
                    </tr>
                </table>
            </div>
            <div id="collapse1" class="accordion-body collapse">
                <div class="accordion-inner">
                    <table class="table table-bordered table-hover table-striped">
                        <tr class="">
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <form class="form-inline" method="post" action="#">
                                    <input type="hidden" value="" name="idtrain">
                                    <input class="idUserInput" type="hidden" value="" name="iduser">
                                    <input type="hidden" value="" name="idparent">
                                    <p><input class="input-large" type="text" placeholder="votre commentaire" name="label"></p>
                                    <p><button type="submit" class="btn btn-primary pull-right submitPushMessage">Envoyer</button></p>
                                </form>
                            </td>

                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="accordion-group">
            <div class="accordion-heading accordion-toggle" data-parent="#accordion2" data-toggle="collapse"  href="#collapsenew">
                <table class="table table-bordered table-hover table-striped">
                    <tr>
                        <td>Nouveau message</td>
                    </tr>
                </table>
            </div>
            <div id="collapsenew" class="accordion-body collapse">
                <div class="accordion-inner">
                    <table class="table table-bordered table-hover table-striped">
                        <tr>
                            <td>        
                                <form class="form-inline" method="post" action="#">
                                    <input type="hidden" value="" name="idtrain">
                                    <input class="idUserInput" type="hidden" value="" name="iduser">
                                    <input type="hidden" value="" name="idparent">
                                    <p><input class="input-large" type="text" placeholder="votre commentaire" name="label"></p>
                                    <p><button type="submit" class="btn btn-primary pull-right submitPushMessage">Envoyer</button></p>
                                </form>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>


</div>