
    <?php   $comulienNamespace = new Zend_Session_Namespace('bulle');
            if (isset($comulienNamespace->checkedInEvent))
            {   
                $event = $comulienNamespace->checkedInEvent->titreEvent;
            }
            else 
            {
                $event = 'Comulien';
            }
    ?>
    <div class="navbar navbar-fixed-top" id="navBar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#" id="nomEvent"><?php echo $event ?></a>
          <a class="btn btn_maj pull-right" id="btn_maj">
              <img id="maj" src="<?php  echo $this->baseUrl(); ?>/images/attente.png"/>
              <div id="nbrMessageRecent"></div>
          </a>
         
          <div class="nav-collapse collapse pull-right">
            <ul class="nav">
              <li><a href="<?php echo $this->accueilEventLink(); ?>">Accueil</a></li>
              <!-- Test si l'utilisateur est loggé-->
              <?php if(isset($_SESSION['Zend_Auth'])){
                  $nomLien = 'Déconnexion';?>
                  <li><a href="<?php echo $this->baseUrl() . '/utilisateur/index' ?>">Profil</a></li>
              <?php 
              
              }
              else
              {
                  $nomLien = 'Connexion'; 
              }
              ?>
              <li><a href="<?php echo $this->profileLink(); ?>"><?php echo $nomLien;?></a></li>
              <li><a href="<?php echo $this->checkoutLink(); ?>">CheckOut</a></li>
            </ul>       
          </div><!--/.nav-collapse -->
          
        </div>
      </div> 
        <div class="container-header">
            <div class="saisieMessage">
               <?php  if (!is_null($this->formEcrireMessage)) {
                    echo $this->formEcrireMessage ;
               }?> 
            </div>
        </div>
   </div>


