
<div>
    <?php foreach ($this->events as $entry): ?>
    <?php //var_dump($entry) ?>
    <p>---------------------------------------------------------------------------------</p>
    <div><a href="<?php echo $this->url(array('module'=>'default', 'controller' => 'evenement','action'=>'checkin','id'=>$entry->idEvent)); ?>" alt=""><?php echo $this->escape($entry->titreEvent) ?></a></div>
    <div>
        <a href="<?php echo $this->url(array('module'=>'default', 'controller' => 'evenement','action'=>'checkin','id'=>$entry->idEvent)); ?>" alt="">
            <img src="<?php echo $this->url(array('module'=>'default', 'controller' => 'qrcode','action'=>'embedded-image','id'=>$entry->idEvent)); ?>" />
            ../qrcode/embedded-image
        </a>
    </div>
    <p><?php echo $this->escape($entry->numEvent) ?></p>
    <p><?php echo $this->escape($entry->descEvent) ?></p>
    <p><?php echo $this->escape($entry->logoEvent) ?></p>
    <p><?php echo $this->escape($entry->dateDebutEvent) ?></p>
    <p><?php echo $this->escape($entry->dateFinEvent) ?></p>
    <p><?php echo $this->escape($entry->delaiPersistence) ?></p>
    <p><?php if($entry->idOrga != null) echo 'Organisme : ' . $this->escape($entry->getOrga()->nomOrga)?></p>
   
    <?php endforeach ?>
</div>