<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>QR Demo</title>
<style type="text/css">
* { font-family: Arial; }
</style>

</head>


<body>

<h2>PNG format</h2>
<img src="../qrcode/embedded-image" /><br />
<a href="../qrcode/download/type/image">Download</a>

<h2>SVG format</h2>
<img src="../qrcode/embedded-svg" /><br />
<a href="../qrcode/download/type/svg">Download</a>

<h2>EPS format</h2>
<a href="../qrcode/download/type/eps">Download</a>

<h2>PDF format</h2>
<a href="./download/type/pdf">Download</a>

</body>
</html>