<br /><br />
<div id="view-content">
	<p>View script for controller <b>Message</b> and script/action name <b>index</b></p>
</div>
Message Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><?php echo $this->escape($entry->dateEmissionMsg) ?></dt>
    <dd><?php echo $this->escape($entry->lblMessage) ?></dd>
    <dd><?php echo $this->escape($entry->dateActiviteMsg) ?></dd>
    <dd><?php echo $this->escape($entry->estActifMsg) ?></dd>
    <dd><?php if($entry->idEvent != null) echo 'Evenement : ' . $this->escape($entry->getEvent()->titreEvent)?></dd>
    <dd><?php if($entry->idTypeMsg != null) echo 'Type du message : ' . $this->escape($entry->getType()->lblTypeMsg)?></dd>
    <dd><?php if($entry->idProfil != null) echo 'Type du profil : ' . $this->escape($entry->getProfil()->nomProfil)?></dd>
    <dd><?php if($entry->idUser_emettre != null) echo 'Emetteur : ' . $this->escape($entry->getUserEmettre()->nomUser)?></dd>
    <dd><?php if($entry->idUser_moderer != null) echo 'Moderateur : ' . $this->escape($entry->getUserModerer()->nomUser)?></dd>
    <?php endforeach ?>
</dl>