<!--
TODO
- Modifier l'image par défaut de gravatar
-->


<?php foreach ($this->messages as $entry): ?>
<!--Affiche le message-->
<div class="message" onclick="javascript:afficher_cacher('message<?php echo $this->escape($entry->idMessage) ?>');">
    <div class="avatar"><?php echo $this->gravatar($entry->getUserEmettre()->emailUser)?> </div>
    <div class="dateMessage"><?php echo $this->escape($this->dateMessage($entry->dateActiviteMsg)) ?></div>
    <div class="nomUser"><?php if($entry->idUser_emettre != null) echo $this->escape($entry->getUserEmettre()->nomUser)?></div>
    <div class="nbMessage"><!--<img class="icone" alt="home" src="<?php echo $this->baseUrl() ?> /images/message.png"/>--><span>23</span></div>
    <div class="lblMessage"><?php echo $this->escape($entry->lblMessage) ?></div></br>
</div>  
<!--Affiche le menu du message-->
<div class="menuMessage" id="message<?php echo $this->escape($entry->idMessage) ?>" >
    <ul>
        <li><a href="" ><img class="icone" alt="home" src="<?php echo $this->baseUrl() ?> /images/rep.png"/></a></li>
         <?php 
            //Recherche et affiche le nombre de plus et de moins d'un message
            $app = $entry->getAppreciers();
            $plus = 0;
            $moins = 0;
             foreach ($app as $appreciation){
                 if($appreciation->evaluation > 0){
                     $plus++;
                 }
                 else{
                     $moins++;
                 }    
             }
             
             
        ?>
        <li><a href="<?php echo$this->likeMessage($entry->idMessage);?>" alt=''><img class="icone" alt="home" src="<?php echo $this->baseUrl() ?> /images/plus.png"/><div id="plus"><?php echo $plus ?></div></a></li>
        <li><a href="<?php echo$this->unlikeMessage($entry->idMessage);?>" ><img class="icone" alt="home" src="<?php echo $this->baseUrl() ?> /images/moins.png"/><div id="moins"><?php echo $moins ?></div></a></li>
        <li><a href="" ><img class="icone" alt="home" src="<?php echo $this->baseUrl() ?> /images/face.png"/></a></li>
        <li><a href="" ><img class="icone" alt="home" src="<?php echo $this->baseUrl() ?> /images/twit.png"/></a></li>
        <?php if($this->moderateur){ ?> <li><a href="<?php echo $this->moderationMessage($entry->idMessage) ?>" ><img class="icone" alt="home" src="<?php echo $this->baseUrl() ?> /images/suppr.png"/></a></li> <?php }?>
    </ul>
</div>

 <!-- Appel de la fonction pour cacher les menus des messages -->
 <script type="text/javascript">
 //<!--
    afficher_cacher('message<?php echo $this->escape($entry->idMessage) ?>');
 //-->
 </script>
    <?php endforeach ?>
 <!-- Test si l'utilisateur est bien loggé -->
    <?php  if (!is_null($this->formEcrireMessage)) {?>
           <div id="menuEcrire" onclick="javascript:afficher_cacher('ecrireMessage');">
               <div id="menuEcrireLien"><img class="bulle" alt="home" src="<?php echo $this->baseUrl() ?> /images/message.png"/></div>
           </div>
           <div id="ecrireMessage">
           <?php echo $this->formEcrireMessage ; ?>
           </div>
           
           
     <?php   }
     ?>      
 <!-- Appel de la fonction pour cacher le formulaire -->
 <script type="text/javascript">
 //<!--
    afficher_cacher('ecrireMessage');
 //-->
 </script>
    
    
 
 
 
 
 
    <!--ANCIEN CODE QUI PEUT SERVIR
    
   
    <div><?php echo 'note : '.$entry->getNote() ?></div>
    <div><?php echo $this->moderationMessage($entry->idMessage) ?></div>
    <dd><?php if($entry->idTypeMsg != null) echo 'Type du message : ' . $this->escape($entry->getType()->lblTypeMsg)?></dd>
    -->
    
    <!--
    <dd><?php echo $this->escape($entry->dateActiviteMsg) ?></dd>
    <dd><?php echo ($entry->estActifMsg=='1')?'Message Actif':'Message inactif' ?> : 
    
            <?php //echo $this->formModererMessage ?></dd>
    <dd><?php if($entry->idEvent != null) echo 'Evenement : ' . $this->escape($entry->getEvent()->titreEvent)?></dd>
     <dd><?php if($entry->idProfil != null) echo 'Type du profil : ' . $this->escape($entry->getProfil()->nomProfil)?></dd>
     <dd><?php if($entry->idUser_moderer != null) echo 'Moderateur : ' . $this->escape($entry->getUserModerer()->nomUser)?></dd>
     <?php 
     echo 'Liste des utilisateurs qui ont appréciés : <br/>';
    //Recherche et affiche les utilisateurs d'un message
    $app = $entry->getAppreciers();
     foreach ($app as $appreciation){
         echo '<dd>Utilisateur : ' . $appreciation->getUser()->loginUser . 
                 ' - Appréciation : ' . $appreciation->evaluation . '</dd>'; 
     }
     ?>-->

 
