<!--
TODO
- Modifier l'image par défaut de gravatar
-->
<div class="container-fluid">
    <div id="reponses">
        <div class="waitGif"><img id="attente<?php echo $entry->idMessage; ?>"  src="<?php  echo $this->baseUrl(); ?>/images/attente.gif"/><span> Chargement en cours...</span></div>
    </div>
        
</div><!--container-fluid-->
<div class="chargerPlusMessage" id="chargerPlusMessage"><a class="chargerPlusMessage" href="">Plus...</a></div>
                          
<script src="<?php echo $this->baseUrl() . '/bootstrap/' ?>js/reponses.js" type="text/javascript"></script>    
<script src="<?php echo $this->baseUrl() . '/bootstrap/' ?>js/plusMessage.js" type="text/javascript"></script>       


   
 
