

<?php foreach ($this->messages as $entry): ?>
    
<ul>
    
    <!--'idEvent','idUser_emettre','idUser_moderer','idMessage','idTypeMsg','lblMessage','estActifMsg','dateEmissionMsg','dateActiviteMsg')-->
    <li>Date d'émission : <?php echo $this->escape($entry->dateEmissionMsg) ?></li>
    <li>Date d'activite : <?php echo $this->escape($entry->dateActiviteMsg) ?></li>
    <li>Message #<?php echo $this->escape($entry->idMessage) ?> : <?php echo $this->escape($entry->lblMessage) ?></li>
    <li>idTypeMessage #<?php echo $this->escape($entry->idTypeMsg) ?></li>
    <li>idUser_emettre #<?php echo $this->escape($entry->idUser_emettre) ?></li>
    <li>Etat <?php echo ($this->escape($entry->estActifMsg)==1)?'Actif':'inactif' ?></li>
    <li>Moderé par <?php echo $this->escape($entry->idUser_moderer) ?></li>
    <li>idEvent #<?php echo $this->escape($entry->lblMessage) ?></li>
    

</ul>
<br />
   <?php endforeach ?> 
