<!--
TODO
- Modifier l'image par défaut de gravatar
-->
<div class="container-fluid">
    <div id="monaccordeon">
        <?php foreach ($this->messages as $entry): ?>
               
                <!--Affiche le message-->
                <div class="accordion-group">
                    <div class="accordion-heading"> <a class="accordion-toggle" href="#menu<?php echo $entry->idMessage; ?>" data-parent="#monaccordeon" data-toggle="collapse">
                        <div class="row-fluid">
                           <div class="span12"> 
                              <div class="avatar"><?php echo $this->gravatar($entry->getUserEmettre()->emailUser)?> </div>
                           
                              <div class="nomUser"><?php if($entry->idUser_emettre != null) echo $this->escape($entry->getUserEmettre()->nomUser)?></div>
                              <div class="dateMessage"><?php echo $this->escape($this->dateMessage($entry->dateActiviteMsg)) ?></div><br/>
                              <div class="lblMessage"><?php echo $this->escape($entry->lblMessage) ?></div>
                              <!--<div class="nbMessage">23</div>-->
                           </div>  
                           
                        </div>
                    </a>
                    </div>
                    <div id="menu<?php echo $entry->idMessage; ?>" class="collapse menuMessage">
                        <div id="monaccordeonMenu">
                            <nav class="navbar">
                                <div class="navbar-inner">
                                  <div class="container">
                                    <ul class="nav">
                                         <?php 
                                            //Recherche et affiche le nombre de plus et de moins d'un message
                                            $app = $entry->getAppreciers();
                                            $plus = 0;
                                            $moins = 0;
                                            foreach ($app as $appreciation){
                                                if($appreciation->evaluation > 0){
                                                    $plus++;
                                                }
                                                else{
                                                    $moins++;
                                                }    
                                            }
                                         ?>

                                        <li><?php echo $this->reponseMessage($entry->idMessage); ?></li>
                                        <li class="divider-vertical"></li>
                                        <li> <a href="<?php echo$this->likeMessage($entry->idMessage);?>"><i class="icon-thumbs-up"></i> <?php echo $plus ?></a> </li>
                                        <li class="divider-vertical"></li>
                                        <li> <a href="<?php echo$this->unlikeMessage($entry->idMessage);?>"><i class="icon-thumbs-down"></i>  <?php echo $moins ?></a> </li>
                                        <!--<li class="divider-vertical"></li>
                                        <li><a href="http://www.facebook.com">Facebook</a></li>
                                        <li class="divider-vertical"></li>
                                        <li><a href="http://www.twitter.com">Twitter</a></li>-->
                                        <?php if($this->moderateur){ ?> 
                                        <li class="divider-vertical"></li>
                                        <li> <a href="<?php echo $this->moderationMessage($entry->idMessage) ?>">Modérer</a> </li><?php }?>
                                    </ul>
                                  </div>
                                </div>
                              </nav>
                            <div id="reponses<?php echo $entry->idMessage; ?>"></div>
                        </div><!--monaccordeon-->
                    </div>
              </div><!--accordion-group-->
         <?php endforeach ?>
    </div><!--monaccordeon-->
</div><!--container-fluid-->



   
 
