<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Comulien');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <link rel="stylesheet" href="css/main.css"/>
        <!DOCTYPE html>
        <!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
        <!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
        <!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
        <!--[if gt IE 8]><!-->
        <!--<![endif]-->
        <meta name="description" content=""/>
        <meta name="viewport" content="width=device-width"/>
        <link rel="stylesheet" href="css/main.css"/>
        <link rel="stylesheet" href="css/bootstrap.css"/>
        <link rel="stylesheet" href="css/bootstrap-responsive.css"/>
        
        <!--  AutoCompletion -->
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">Comulien</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="home.php">Inscription</a></li>

                            <li id="navAuthentifie" style="display:none;"class="dropdown">
                                <a id="nomUser" href="#" class="dropdown-toggle" data-toggle="dropdown">?<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Mon profil</a></li>
                                    <li><a id="aDeconnexion" href="#">Deconnexion</a></li>
                                </ul>

                            </li>

                        </ul>
                        <div id="navAuthentification">
                            <form class="navbar-form pull-right">
                                <input id="userIdentification" class="span2" type="text" placeholder="e-mail"/>
                                <input id="passIdentification" class="span2" type="password" placeholder="mot de passe"/>
                                <button id="submitIdentification" type="submit" class="btn">Go!</button>
                            </form>
                        </div>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <?php echo $this->layout()->content; ?>
    </body>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.8.2.min.js"><\/script>')</script>
    <script src="js/vendor/bootstrap.min.js"></script>
    <script src="js/main.js"></script>
    <script src="js/jqtouch.min.js"></script>
    
</html>