    <!-- application/layouts/scripts/layout.phtml -->
    <?php echo $this->doctype() ?>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>Comulien</title>
      <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/main.css') ?>
      
    </head>
    <body>
    <?php echo $this->render('header/header.phtml'); ?>
    <?php echo $this->layout()->content ?>
    <?php echo $this->render('footer/footer.phtml'); ?>
    </body>
    </html>