    <!-- application/layouts/scripts/layout.phtml -->
    <?php echo $this->doctype() ?>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta name="viewport" content="user-scalable=no, initial-scale = 1, minimum-scale = 1, maximum-scale = 1, width=device-width">
      <title>Comulien</title>
            <link href="/comuZend/public/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
            <link href="/comuZend/public/bootstrap/css/main.css" rel="stylesheet" type="text/css" />

      <style>
          body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
          }
      </style>
      <link href="/comuZend/public/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css" />
      
      <link rel="shortcut icon" href="<?php echo $this->baseUrl() . '/bootstrap/' ?>ico/favicon.ico">
      <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->baseUrl() . '/bootstrap/' ?>ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->baseUrl() . '/bootstrap/' ?>ico/apple-touch-icon-72-precomposed.png">
      <link rel="apple-touch-icon-precomposed" href="<?php echo $this->baseUrl() . '/bootstrap/' ?>ico/apple-touch-icon-57-precomposed.png">
   
    </head>
    <body>
        
    <?php echo $this->render('header/header.phtml'); ?>
    <?php echo $this->layout()->content ?>
    <?php echo $this->render('footer/footer.phtml'); ?>
    </body>
    </html>