    <!-- application/layouts/scripts/layout.phtml -->
    <?php echo $this->doctype() ?>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta name="viewport" content="user-scalable=no, initial-scale = 1, minimum-scale = 1, maximum-scale = 1, width=device-width">
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

      <title>Comulien</title>
            <link href="<?php echo $this->baseUrl() . '/bootstrap/' ?>css/bootstrap.css" rel="stylesheet" type="text/css" />
        <style>
          body {
            padding-top: 75px; /* 75px place le content tjrs en dessous de la barre de navigation */
          }
      </style>
          <link href="<?php echo $this->baseUrl() . '/bootstrap/' ?>css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
          <link href="<?php echo $this->baseUrl() . '/bootstrap/' ?>css/main.css" rel="stylesheet" type="text/css" />
          <script src="<?php echo $this->baseUrl() . '/bootstrap/js/' ?>jquery.js" type="text/javascript"></script> 
          <script type="text/javascript">
              var BASE_URL = '<?php echo $this->baseUrl(); ?>';
          </script>
          <script src="<?php echo $this->baseUrl() . '/bootstrap/' ?>js/bootstrap.js"></script>
          <link rel="shortcut icon" href="<?php echo $this->baseUrl() . '/bootstrap/' ?>img/favicon.ico">
          <link rel="glyphicons-halflings" sizes="114x114" href="<?php echo $this->baseUrl() . '/bootstrap/' ?>img/glyphicons-halflings">
          <link rel="glyphicons-halflings" sizes="72x72" href="<?php echo $this->baseUrl() . '/bootstrap/' ?>img/glyphicons-halflings">
          <link rel="glyphicons-halflings" href="<?php echo $this->baseUrl() . '/bootstrap/' ?>img/glyphicons-halflings"> 
          </head>
    <body>
        
    <?php echo $this->render('header/header.phtml'); ?>
    <?php echo $this->layout()->content ?>
    <?php echo $this->render('footer/footer.phtml'); ?>
    </body>
    </html>