<h3>Liste des utilisateurs</h3>
<table>
    <tr>
        <th>id</th>
        <th>login</th>
        <th>psw</th>
        <th>email</th>
        <th>inscription</th>
        <th>nb msg</th>
        <th>nb approuv</th>
        <th>actif</th>
    </tr>
    <?php foreach($this->users as $user) : ?>
        <tr>
            <td><?php echo $user->IDUSER; ?></td>
            <td><?php echo $user->LOGINUSER; ?></td>
            <td><?php echo $user->PSWUSER; ?></td>
            <td><?php echo $user->EMAILUSER; ?></td>
            <td><?php echo $user->DATEINSCRIPTIONUSER; ?></td>
            <td><?php echo $user->NBMSGUSER; ?></td>
            <td><?php echo $user->NBAPPROUVUSER; ?></td>
            <td><?php echo $user->ESTACTIFUSER; ?></td>
        </tr>
    <?php endforeach; ?>
</table>
