<br /><br />
<div id="view-content">
    <ul>
        <li><img src="<?php echo $this->escape($this->utilisateur->getGravatar()) ?>" alt="" /></li>
        <li>Bienvenue <?php echo $this->escape($this->utilisateur->prenomUser) ?> <?php echo $this->escape($this->utilisateur->nomUser) ?></li>
        <li>Inscrit le <?php echo $this->escape($this->utilisateur->dateInscriptionUser) ?></li>
        <li>Dans l'évènement '<?php echo $this->escape($this->evenement->titreEvent) ?>' vous êtes '<?php echo $this->escape($this->role) ?>'
            <b><?php echo ($this->moderateur)?'avec':'sans'; ?></b> pouvoir de modération.</li>
        <li><a href="<?php echo $this->baseUrl() . '/utilisateur/modifier' ?>">Editer mes informations</a></li>
        <li><a href="<?php echo $this->baseUrl() . '/utilisateur/profilpublic/id/'. $this->utilisateur->idUser ?>">Voir mon profil public</a></li>
        <li><a href="<?php echo $this->baseUrl() . '/utilisateur/profilprive' ?>">Voir mon profil complet</a></li>
        <li><a href="<?php echo $this->baseUrl() . '/utilisateur/deconnecter' ?>">Me déconnecter</a></li>
        <li>TODO : si organisateur de l'évènement en cours : proposer d'éditer l'évènement</li>
    </ul>  
</div>
<!--
Utilisateur Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <p>---------------------------------------------------------------------------------</p>
    <dt><?php echo $this->escape($entry->loginUser) ?></dt>
    <dd><img src="<?php echo $this->escape($entry->getGravatar()) ?>" alt="" /></dd>
    <dd><?php echo $this->escape($entry->pswUser) ?></dd>
    <dd><?php echo $this->escape($entry->emailUser) ?></dd>
    <dd><?php echo $this->escape($entry->dateInscriptionUser) ?></dd>
    <dd><?php echo $this->escape($entry->nomUser) ?></dd>
    <dd><?php echo $this->escape($entry->prenomUser) ?></dd>
    <dd><?php echo $this->escape($entry->nbMsgUser) ?></dd>
    <dd><?php echo $this->escape($entry->nbApprouverUser) ?></dd>
    <dd><?php echo $this->escape($entry->estActifUser) ?></dd>
    <?php 
     echo 'Liste des messages émis : <br/>';
    //Recherche et affiche les messages
    $mess = $entry->getMessagesEmis();
     foreach ($mess as $message){
         echo '<dd>Message : ' . $message->lblMessage . '</dd>'; 
     }
     ?>
     <?php 
     echo 'Liste des messages appréciés : <br/>';
    //Recherche et affiche les messages
    $app = $entry->getAppreciers();
     foreach ($app as $appreciation){
         echo '<dd>Message : ' . $appreciation->getMessage()->lblMessage . 
                 ' - Appréciation : ' . $appreciation->evaluation . '</dd>'; 
     }
     ?>
    <?php 
     echo 'Liste des organismes : <br/>';
    //Recherche et affiche les utilisateurs d'un organisme
    $dist = $entry->getDistinctions();
     foreach ($dist as $distinction){
         echo '<dd>Organisme : ' . $distinction->getOrganisme()->nomOrga . 
                 ' - Profil : ' . $distinction->getProfil()->nomProfil . 
                 ' - Droit modération : ' . $distinction->droitModeration . 
                 ' - Fonction : ' . $distinction->nomFonction . '</dd>'; 
     }
     ?>
    <?php endforeach ?>
</dl>
-->